# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='share_restrict',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='限售A股'),
        ),
    ]
