# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20180520_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, verbose_name='股票代码')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='年份')),
                ('time', models.PositiveSmallIntegerField(choices=[(1, '第一季度财报'), (2, '第二季度财报'), (3, '第三季度财报'), (4, '第四季度财报'), (5, '半年财报'), (6, '全年财报')], db_index=True, verbose_name='财报时间')),
                ('eps', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='每股收益')),
                ('bps', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='每股净资产')),
                ('gross_earnings_per_share', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='每股营业总收入')),
                ('capital_stock_per_share', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='每股资本公积')),
                ('earnings_per_share', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='每股盈余公积')),
                ('undistributed_profit_per_share', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='每股未分配利润')),
                ('pre_tax_earnings_per_share', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='每股税前利润')),
                ('ebitda', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='每股EBITDA')),
                ('pe', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='市盈率')),
                ('roe', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='净资产收益率')),
                ('roa', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='总资产报酬率')),
                ('roic', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='投入资本回报率')),
                ('gross_profit_margin', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='销售毛利率')),
                ('net_profit_margin', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='销售净利率')),
                ('opt_oebt', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='主营业务比率')),
                ('debt_to_assets', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='资产负债率')),
                ('long_debt_to_long_captial', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='长债负债率')),
                ('short_debt_to_long_captial', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='短债负债率')),
                ('assets_to_equity', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='权益乘数')),
                ('fa_current', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='流动比率')),
                ('fa_quick', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='速动比率')),
                ('fa_cash_to_current_debt', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='现金比率')),
                ('fa_debt_to_equity', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='产权比率')),
                ('fa_invturn', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='存货周转率')),
                ('fa_arturn', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='应收转款周转率')),
                ('fa_assets_turn', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='总资产周转率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '财务因子',
                'verbose_name_plural': '财务因子',
            },
        ),
        migrations.AlterUniqueTogether(
            name='financialfactor',
            unique_together=set([('code', 'year', 'time')]),
        ),
    ]
